module.exports = (sequelize, DataTypes) => {
  const SalesOrderTransaction = sequelize.define("SalesOrderTransaction", {
    sales_order_id: { type: DataTypes.INTEGER, allowNull: false },
    product_id: { type: DataTypes.INTEGER, allowNull: false },
    product_description: { type: DataTypes.TEXT },
    product_specification: { type: DataTypes.TEXT },
    product_unit: { type: DataTypes.INTEGER },
    product_qty: { type: DataTypes.DECIMAL(10,2) },
    product_base_unit: { type: DataTypes.INTEGER },
    product_base_qty: { type: DataTypes.DECIMAL(10,2) },
    product_convert_unit: { type: DataTypes.INTEGER },
    product_convert_qty: { type: DataTypes.DECIMAL(10,2) },
    product_amount: { type: DataTypes.DECIMAL(12,2) },
    product_convert_amount: { type: DataTypes.DECIMAL(12,2) },
    discount_per: { type: DataTypes.DECIMAL(5,2) },
    discount_amount: { type: DataTypes.DECIMAL(12,2) },
    discount_convert_amount: { type: DataTypes.DECIMAL(12,2) },
    tax_1_name: { type: DataTypes.STRING(50) },
    tax_1_amount: { type: DataTypes.DECIMAL(12,2) },
    tax_2_name: { type: DataTypes.STRING(50) },
    tax_2_amount: { type: DataTypes.DECIMAL(12,2) },
    tax_3_name: { type: DataTypes.STRING(50) },
    tax_3_amount: { type: DataTypes.DECIMAL(12,2) },
    quotation_transaction_id: { type: DataTypes.INTEGER },
    production_status: { type: DataTypes.TINYINT },
    production_qty: { type: DataTypes.DECIMAL(10,2) },
    production_branch_id: { type: DataTypes.INTEGER },
    bom_id: { type: DataTypes.INTEGER },
    delivery_type: { type: DataTypes.TINYINT },
    delivery_date: { type: DataTypes.DATE },
    bom_status: { type: DataTypes.TINYINT },
    invoice_status: { type: DataTypes.TINYINT },
    invoice_id: { type: DataTypes.INTEGER },
    remaning_invoice_qty: { type: DataTypes.DECIMAL(10,2) },
    remaning_invoice_convert_qty: { type: DataTypes.DECIMAL(10,2) },
    dispatch_status: { type: DataTypes.TINYINT },
    dispatch_id: { type: DataTypes.INTEGER },
    remaning_dispatch_qty: { type: DataTypes.DECIMAL(10,2) },
    remaning_dispatch_convert_qty: { type: DataTypes.DECIMAL(10,2) },
    is_allocated: { type: DataTypes.TINYINT },
    product_tax_category_id: { type: DataTypes.INTEGER },
    cgst_percentage: { type: DataTypes.DECIMAL(5,2) },
    cgst_rate: { type: DataTypes.DECIMAL(12,2) },
    cgst_rate_convert: { type: DataTypes.DECIMAL(12,2) },
    sgst_percentage: { type: DataTypes.DECIMAL(5,2) },
    sgst_rate: { type: DataTypes.DECIMAL(12,2) },
    sgst_rate_convert: { type: DataTypes.DECIMAL(12,2) },
    igst_percentage: { type: DataTypes.DECIMAL(5,2) },
    igst_rate: { type: DataTypes.DECIMAL(12,2) },
    igst_rate_convert: { type: DataTypes.DECIMAL(12,2) },
    returnable_status: { type: DataTypes.TINYINT },
    prev_sales_order_id: { type: DataTypes.INTEGER },
    short_close_status: { type: DataTypes.TINYINT },
    short_close_unit_id: { type: DataTypes.INTEGER },
    short_close_qty: { type: DataTypes.DECIMAL(10,2) },
    total_amount: { type: DataTypes.DECIMAL(12,2) },
    total_convert_amount: { type: DataTypes.DECIMAL(12,2) },
    priority: { type: DataTypes.STRING(10) },
    sales_order_transaction_status: { type: DataTypes.TINYINT },
    user_id: { type: DataTypes.INTEGER, allowNull: false },
    branch_id: { type: DataTypes.INTEGER, allowNull: false },
    company_id: { type: DataTypes.INTEGER, allowNull: false },
    status: {
      type: DataTypes.TINYINT,
      defaultValue: 0,
      comment: "0:Active, 1:Inactive, 2:Deleted"
    }
  }, {
    tableName: "sales_order_transaction",
    timestamps: true,
    underscored: true
  });

  return SalesOrderTransaction;
};
