const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const CompanyConfigration = sequelize.define('companyConfigration', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  enable_cost_center: DataTypes.BOOLEAN,
  enable_party_dashboard: DataTypes.BOOLEAN,
  enable_bank_reconcilation: DataTypes.BOOLEAN,
  enablae_pdc: DataTypes.BOOLEAN,
  enable_month_budget: DataTypes.BOOLEAN,
  enable_depreciation: DataTypes.BOOLEAN,
  enable_multi_currency: DataTypes.BOOLEAN,
  enable_salesman: DataTypes.BOOLEAN,
  enable_transport: DataTypes.BOOLEAN,
  enable_billby_bill_blnc: DataTypes.BOOLEAN,
  enable_scheme: DataTypes.BOOLEAN,
  enable_paramter_stock: DataTypes.BOOLEAN,
  enable_batch_stock: DataTypes.BOOLEAN,
  enable_serial_stock: DataTypes.BOOLEAN,
  enable_mrp_stock: DataTypes.BOOLEAN,
  enable_free_qty: DataTypes.BOOLEAN,
  enable_negative_qty: DataTypes.BOOLEAN,
  enable_voucher_approval: DataTypes.BOOLEAN,
  enable_sms: DataTypes.BOOLEAN,
  enable_email: DataTypes.BOOLEAN,
  enable_tds_reporting: DataTypes.BOOLEAN,
  enable_tcs_reporting: DataTypes.BOOLEAN,
  enable_eway_bill: DataTypes.BOOLEAN,
  enable_einvoice: DataTypes.BOOLEAN,
  enable_gst_filling: DataTypes.BOOLEAN,
  gsp_username: DataTypes.STRING,
  gsp_password: DataTypes.STRING,
  crm_pro_type: DataTypes.STRING,
  so_pro_type: DataTypes.STRING,
  indent_po_pro_type: DataTypes.STRING,
  production_pro_type: DataTypes.STRING,
  inventory_pro_type: DataTypes.STRING,
  stock_pro_type: DataTypes.STRING,
  resource_pro_type: DataTypes.STRING,
  item_mst_pro_type: DataTypes.STRING,
  service_pro_type: DataTypes.STRING,
  upload_reciept: DataTypes.STRING,
  qc_upload_receipt: DataTypes.STRING,
  crm_pro_search: DataTypes.STRING,
  production_pro_search: DataTypes.STRING,
  purchase_pro_search: DataTypes.STRING,
  sales_pro_search: DataTypes.STRING,
  bom_pro_search: DataTypes.STRING,
  resource_pro_search: DataTypes.STRING,
  item_mst_pro_search: DataTypes.STRING,
  service_pro_search: DataTypes.STRING,
  crm_pro_print: DataTypes.STRING,
  production_pro_print: DataTypes.STRING,
  purchase_pro_print: DataTypes.STRING,
  sales_pro_print: DataTypes.STRING,
  bom_pro_print: DataTypes.STRING,
  resource_pro_print: DataTypes.STRING,
  sales_time_load_pro: DataTypes.BOOLEAN,
  sales_party_show: DataTypes.STRING,
  purchase_party_show: DataTypes.STRING,
  inventory_party_show: DataTypes.STRING,
  generate_item_code: DataTypes.BOOLEAN,
  item_code_generate: DataTypes.BOOLEAN,
  common_item_diff_company: DataTypes.BOOLEAN,
  party_code_generate: DataTypes.BOOLEAN,
  multiple_make_item_master: DataTypes.BOOLEAN,
  enable_consolidate_so_item: DataTypes.BOOLEAN,
  design_department: DataTypes.BOOLEAN,
  design_so_customization: DataTypes.BOOLEAN,
  po_terms_conditions: DataTypes.BOOLEAN,
  enable_assing_user: DataTypes.BOOLEAN,
  trading_stock: DataTypes.BOOLEAN,
  ledger_code: DataTypes.BOOLEAN,
  enable_consolidate_item: DataTypes.BOOLEAN,
  gross_balance_limit: DataTypes.DECIMAL(15,5),
  batch_wise_stock: DataTypes.BOOLEAN,
  batch_no_stock: DataTypes.BOOLEAN,
  store_approval: DataTypes.BOOLEAN,
  outside_jobwork: DataTypes.BOOLEAN,
  grn_sticker_print: DataTypes.BOOLEAN,
  batch_type: DataTypes.BOOLEAN,
  batch_process: DataTypes.BOOLEAN,
  crm_user_type: DataTypes.STRING,
  po_work_order_wise: DataTypes.BOOLEAN,
  direct_po_create: DataTypes.BOOLEAN,
  enable_post_crm: DataTypes.BOOLEAN,
  crm_task_order: DataTypes.STRING,
  enable_quotation_limit: DataTypes.BOOLEAN,
  quotation_disc_limit: DataTypes.BOOLEAN,
  enable_inquiry_autoclose: DataTypes.BOOLEAN,
  inquiry_autoclose_limit: DataTypes.BOOLEAN,
  batch_stock: DataTypes.BOOLEAN,
  enable_count_outstanding_target: DataTypes.BOOLEAN,
  enable_task_crm: DataTypes.BOOLEAN,
  production_start_type: DataTypes.BOOLEAN,
  stock_type_a: DataTypes.STRING,
  stock_type_b: DataTypes.STRING,
  stock_type_c: DataTypes.STRING,
  gross_balance_tds_limit: DataTypes.DECIMAL(15,5),
  enable_hypothication: DataTypes.BOOLEAN,
  po_document_required: DataTypes.BOOLEAN,
  workorder_planning: DataTypes.BOOLEAN,
  production_start_stop_time: DataTypes.BOOLEAN,
  sending_blue_api_key: DataTypes.STRING,
  sendinblue_mail_id: DataTypes.STRING,
  inq_product_required: DataTypes.BOOLEAN,
  tax_editable: DataTypes.BOOLEAN,
  grn_diff_from_po: DataTypes.INTEGER,
  so_description_required: DataTypes.INTEGER,
  resource_time: DataTypes.INTEGER,
  shift_count: DataTypes.INTEGER,
  shift_days: DataTypes.STRING,
  resource_display: DataTypes.INTEGER,
  automrp_display: DataTypes.INTEGER,
  batchno_as_grnno: DataTypes.INTEGER,
  quotation_rate_fixed: DataTypes.INTEGER,
  sales_wise_branch_planning: DataTypes.INTEGER,
  automatic_approval_indent: DataTypes.INTEGER,
  automatic_approval_po: DataTypes.INTEGER,
  automatic_finance_approval_po: DataTypes.INTEGER,
  automatic_shortclose_approval_po: DataTypes.INTEGER,
  automatic_approval_quotation: DataTypes.INTEGER,
  automatic_approval_proforma: DataTypes.INTEGER,
  automatic_approval_so: DataTypes.INTEGER,
  automatic_approval_order_acceptance: DataTypes.INTEGER,
  enable_item_description: DataTypes.INTEGER,
  enable_item_image: DataTypes.INTEGER,
  inquiry_user_lock: DataTypes.INTEGER,
  ewb_username: DataTypes.STRING(150),
  ewb_password: DataTypes.STRING(150),
  einv_username: DataTypes.STRING(150),
  einv_password: DataTypes.STRING(150),
  trans_dash_user_type: DataTypes.STRING(500),
  header_logo: DataTypes.STRING(150),
  header_text: DataTypes.STRING(150),
  enable_material_center: DataTypes.INTEGER,
  so_invo_descri_transfer: DataTypes.INTEGER,
  branch_wise_manage: DataTypes.INTEGER,
  default_branch_id: DataTypes.INTEGER,
  crm_print_letterhead_per: DataTypes.INTEGER,
  purchase_print_letterhead_per: DataTypes.INTEGER,
  finance_print_letterhead_per: DataTypes.INTEGER,
  sales_print_letterhead_per: DataTypes.INTEGER,
  production_print_letterhead_per: DataTypes.INTEGER,
  enable_installation_type: DataTypes.INTEGER,
  forecast_base: {
    type: DataTypes.INTEGER,
    defaultValue: 1
  },
  so_discount_editable: DataTypes.INTEGER,
  so_calculation_discount_show: DataTypes.INTEGER,
  invoice_discount_editable: DataTypes.INTEGER,
  invoice_calculation_discount_show: DataTypes.INTEGER,
  quotation_header_content: DataTypes.TEXT,
  so_header_content: DataTypes.TEXT,
  po_header_content: DataTypes.TEXT,
  invoice_header_content: DataTypes.TEXT,
  rejection_pro_type: DataTypes.STRING(200),
  crm_sales_order_user_selecation: DataTypes.INTEGER,
  crm_sales_order_user_type_selecation: DataTypes.STRING(500),
  forecast_calculation: {
    type: DataTypes.INTEGER,
    defaultValue: 1
  },
  sales_wise_branch_planning_before_bom: DataTypes.INTEGER,
  quot_revise_time_rate_with_discount: DataTypes.INTEGER,
  store_relese_first_process: DataTypes.INTEGER,
  smpl_batch_prefix: DataTypes.STRING(100),
  resource_wise_production: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  round_up_qty: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  workorder_wise_production_merge: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  process_end_time_qc: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  extra_stock: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  bom_extra_no: DataTypes.STRING(50),
  sales_order_print_after_approval: DataTypes.INTEGER,
  label_print_process_id: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  supplier_tc_no: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  heat_no_saperator: DataTypes.STRING(200),
  followup_inquiry_show: DataTypes.INTEGER,
  packing_module: DataTypes.INTEGER,
  direct_sales_allocate: DataTypes.INTEGER,
  category_selection_active: DataTypes.INTEGER,
  cat_wise_product_load: DataTypes.INTEGER,
  closing_date_diff: DataTypes.STRING(10),
  inq_name_using_comapany: DataTypes.INTEGER,
  wo_bw_alloc_stock: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  smpl_dl_no: DataTypes.STRING(50),
  jobwork_grn: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  smpl_mfg_licence: DataTypes.STRING(100),
  ip_add_login: DataTypes.INTEGER,
  so_product_import: DataTypes.INTEGER,
  customer_show_in_production: {
    type: DataTypes.INTEGER,
    defaultValue: 0
  },
  so_temp_auto_allocate: DataTypes.INTEGER,
  production_on_dashboard: {
    type: DataTypes.INTEGER,
    defaultValue: 1
  },
  enable_old_dashbord: DataTypes.INTEGER,
  set_reserve_godown: DataTypes.INTEGER,
  default_godown_id: DataTypes.INTEGER,
  qc_unit: {
    type: DataTypes.INTEGER,
    defaultValue: 2
  },
  enable_whatsapp: DataTypes.TINYINT,
  whatsapp_api_url: DataTypes.TEXT,
  whatsapp_api_key: DataTypes.TEXT,
  whatsapp_template: DataTypes.STRING(255),
  usertype_id: DataTypes.INTEGER,
  status: {
    type: DataTypes.TINYINT,
    defaultValue: 0,
    comment: '0 = active, 1 = inactive, 2 = deleted'
  },
  user_id: {
    type: DataTypes.INTEGER,
    allowNull: true
  },
  branch_id: {
    type: DataTypes.INTEGER,
    allowNull: true
  },
  company_id: {
    type: DataTypes.INTEGER,
    allowNull: true
  }
}, {
  tableName: 'company_configration',
  timestamps: true,
  underscored: true
});

module.exports = CompanyConfigration;
